version: '2'
services:

  traefik:
    image: traefik:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pms-aws-cloudformation/traefik.toml:/traefik.toml
      - /tmp/pms-aws-cloudformation/.htpasswd:/.htpasswd
      - /cache/config/letsencrypt/acme.json:/acme.json
    container_name: traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.port=8080'
      - 'traefik.frontend.rule=Host:traefik.${HOST_NAME}'

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    volumes:
      - '${CONFIG_DIRECTORY_PATH}/plex:/config'
      - '${DATA_DIRECTORY_PATH}/TV:/data/tvshows'
      - '${DATA_DIRECTORY_PATH}/Movies:/data/movies'
      - '${DATA_DIRECTORY_PATH}/Music:/data/music'
    ports: 
      - '32400:32400/tcp'
      - '3005:3005/tcp'
      - '8324:8324/tcp'
      - '32469:32469/tcp'
      - '1900:1900/udp'
      - '32410:32410/udp'
      - '32412:32412/udp'
      - '32413:32413/udp'
      - '32414:32414/udp'
    env_file: uidgid.env
    restart: always
    # network_mode: host
    networks: 
      - web
      - default
    labels:
      - 'traefik.backend=plex'
      - 'traefik.docker.network=web'
      - 'traefik.frontend.rule=Host:plex.${HOST_NAME}'
      - 'traefik.enable=true'
      - 'traefik.port=32400'

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - '${CONFIG_DIRECTORY_PATH}/nzbget:/config'
      - '${DOWNLOADS_DIRECTORY_PATH}:/downloads'
    expose: 
      - '6789'
    env_file: uidgid.env
    restart: always
    networks: 
      - web
      - default
    labels:
      - 'traefik.backend=nzbget'
      - 'traefik.docker.network=web'
      - 'traefik.frontend.rule=Host:nzbget.${HOST_NAME}'
      - 'traefik.enable=true'
      - 'traefik.port=6789'
    
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    volumes:
      - '${CONFIG_DIRECTORY_PATH}/sonarr:/config'
      - '/etc/localtime:/etc/localtime:ro'
      - '${DATA_DIRECTORY_PATH}/TV:/tv'
      - '${DOWNLOADS_DIRECTORY_PATH}:/downloads'
    expose:
      - '8989'
    env_file: uidgid.env
    restart: always
    networks: 
      - web
      - default
    labels:
      - 'traefik.backend=sonarr'
      - 'traefik.docker.network=web'
      - 'traefik.frontend.rule=Host:sonarr.${HOST_NAME}'
      - 'traefik.enable=true'
      - 'traefik.port=8989'
  
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - '${CONFIG_DIRECTORY_PATH}/radarr:/config'
      - '${DATA_DIRECTORY_PATH}/Movies:/movies'
      - '${DOWNLOADS_DIRECTORY_PATH}:/downloads'
      - '/etc/localtime:/etc/localtime:ro'
    expose: 
      - '7878'
    env_file: uidgid.env
    restart: always
    networks: 
      - web
      - default
    labels:
      - 'traefik.backend=radarr'
      - 'traefik.docker.network=web'
      - 'traefik.frontend.rule=Host:radarr.${HOST_NAME}'
      - 'traefik.enable=true'
      - 'traefik.port=7878'

  plexpy:
    image: linuxserver/tautulli
    container_name: plexpy
    volumes:
      - '${CONFIG_DIRECTORY_PATH}/plexpy:/config'
      - '/etc/localtime:/etc/localtime:ro'
      - '/cache/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro'
    expose:
      - '8181'
    env_file: uidgid.env
    restart: always
    networks: 
      - web
      - default
    labels:
      - 'traefik.backend=plexpy'
      - 'traefik.docker.network=web'
      - 'traefik.frontend.rule=Host:plexpy.${HOST_NAME}'
      - 'traefik.enable=true'
      - 'traefik.port=8181'

  # organizr:
  #   image: lsiocommunity/organizr
  #   container_name: organizr
  #   volumes:
  #     - '${CONFIG_DIRECTORY_PATH}/organizr:/config'
  #   expose:
  #     - '80'
  #   env_file: uidgid.env
  #   restart: always
  #   networks: 
  #     - web
  #     - default
  #   labels:
  #     - 'traefik.backend=organizr'
  #     - 'traefik.docker.network=web'
  #     - 'traefik.frontend.rule=Host:home.${HOST_NAME}'
  #     - 'traefik.enable=true'
  #     - 'traefik.port=80'

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    volumes:
      - '${CONFIG_DIRECTORY_PATH}/heimdall:/config'
    expose:
      - '80'
      - '443'
    env_file: uidgid.env
    restart: always
    networks: 
      - web
      - default
    labels:
      - 'traefik.backend=heimdall'
      - 'traefik.docker.network=web'
      - 'traefik.frontend.rule=Host:home.${HOST_NAME}'
      - 'traefik.enable=true'
      - 'traefik.port=443'
      - 'traefik.protocol=https'

  portainer:
    image: portainer/portainer
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${CONFIG_DIRECTORY_PATH}/portainer_data:/data'
    expose:
      - '9000'
    env_file: uidgid.env
    restart: always
    networks: 
      - web
      - default
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.docker.network=web'
      - 'traefik.frontend.rule=Host:portainer.${HOST_NAME}'
      - 'traefik.enable=true'
      - 'traefik.port=9000'

networks:
  web:
    external: true
